### PR TITLE
Update and unify Spanish translation

### PR DESCRIPTION
**Pull request by oscfdezdz**

### CODE REVIEW

**Comment by oscfdezdz** [comment]
Lines in `data/com.github.huluti.Curtail.appdata.xml.in` aren't included in `po/curtail.pot`, should't those be there as well? When .pot is manually generated with ninja, they show up.

**Comment by oscfdezdz** [comment]
Most of the lines in `data/com.github.huluti.Curtail.appdata.xml.in` are missing in `po/curtail.pot`, should't those be there as well? When .pot is generated with ninja, they show up.

**Comment by Huluti** [comment]
Thank for your work. 

> 
> 
> Most of the lines in `data/com.github.huluti.Curtail.appdata.xml.in` are missing in `po/curtail.pot`, should't those be there as well? When .pot is generated with ninja, they show up.

These are the changelog related lines. I've removed them in acc6665b0a7bd819fa6bea80d9c09d56f28b2cf0. 
I don't really know if we should include them or not, or if we can exclude them from the ninja generation.

**Comment by oscfdezdz** [comment]
Oh, I didn't notice https://github.com/Huluti/Curtail/commit/acc6665b0a7bd819fa6bea80d9c09d56f28b2cf0. 

I don't mind translating those lines, I guess they have to be regularly updated and before every release to every available language which could be a hustle, but at the same time having them translated looks better on software apps stores :)

**Comment by Huluti** [comment]
Indeed it's involve more work. I don't mind adding them back either if that can help. I'll do that this evening.

**Pull request merged**
