### PR TITLE
Webp support

### PR DESCRIPTION
**Pull request by olokelo**
I made Curtail to fully support webp image format via [cwebp](https://developers.google.com/speed/webp/docs/cwebp).
It can now compress .webp files as well as convert .jpg/.png to .webp lossy or losslessly.

**Why?**
WebP is a modern image codec derived from VP8 [widely](https://caniuse.com/webp) supported by major web browsers and operating systems ([decoding since Android 4.0](https://developer.android.com/guide/topics/media/media-formats#image-formats)). It is also arguably better than jpg and png, usually gives smaller file size without artifacts.

It doesn't change the way Curtail works, just adds new functionality which can be disabled via switch on main page.
I also added a button to remove old photos after compression and ability to scale images using cwebp's built-in image resizer.

### CODE REVIEW

**Comment by Huluti** [comment]
Thank you very much! I was aiming to add WebP support when I have time, so glad you got to work on it. Give me a little time to go through everything and to merge this :)

**Comment by akozlovskiy119** [comment]
Some thoughts on UI/UX, I hope @Huluti will give his opinion on that as well:

- Instead of using "image(s)" it is better to correctly handle plurals. When there is one image it should say "image" and when there are many it should say "images" without brackets. Non-English languages plural forms should be handled too. Moreover, I don't think this button is necessary, because there is already an option to overwrite original file, which is more explicit. Also, the button is prone to misclick and doesn't display confirmation dialogue. Accidentally losing original images is the worst thing that could happen, it should be prevented any way possible.
- As I understand Curtail is not a converter, but a compressor. And the basic guarantee is that compressed output has the same format as the original input. Converting JPEG/PNG to WebP is probably a task for another app (For example, Curtail can't convert JPEG to PNG and vice-versa). What if more formats would be added to Curtail in the future? Should they be convertible to WebP? The same applies to scaling. There has to be a basic set of guarantees for every format -- either this functionality (conversion from any format to any other, scaling) should be available for all formats, or not available at all.

**Comment by olokelo** [comment]
Thanks for your suggestions. I know that Curtail is a compressor not a converter so if @Huluti thinks that the conversion between formats should not be available I can remove this functionality. 
I thought that if cwebp can take JPG and PNG as input formats without any external dependencies, it could also be possible in Curtail. The same goes for resizing. Converting from JPG or PNG to WebP also usually lowers the image file size. 
I don't know what's @Huluti's opinion on the button to remove images but I can either remove it or make some warning popup before removing.

**Comment by Huluti** [comment]
Hi! Thank you for your work and your comments. Here's my thoughts:

- I think that @akozlovskiy119 is right when he says that Curtail should remain a "Compressor" soft. So, I'm ok to add the ability to compress WebP images but not to add the conversion and resize feature.

I am committed to keeping the interface as simple as possible. In terms of design we should have #66 in mind for the future.
- So I don't like the idea of the "Delete original image(s)" button. Someone who wants to delete the original image could do it in the file manager with its own responsibility. You can remove it.

Thank you again for your work :) If you make these changes, I'll be very happy to add WebP compression to Curtail! Have a good weekend.

**Comment by olokelo** [comment]
Hi! Sorry for late reply. This week was quite busy for me.

I stripped all unnecessary things I've added before. Now it's as simple as it can be.

Thanks and have a good day/night :)

**Comment by Huluti** [comment]
A bit busy for me these times also... Thank's for the rework :) I'll review the MR in the week.

**Comment by Huluti** [comment]
I'll review the MR this evening. ;)

**Comment by Huluti** [comment]
The PR is perfect! Thank you very much again :)

**Pull request merged**
