### PR TITLE
Created PPA and update README

### PR DESCRIPTION
**Pull request by apandada1**
I have created a PPA for Ubuntu 18.04 and above. I am watching releases, and I would update it when a new version is released.

https://code.launchpad.net/~apandada1/+archive/ubuntu/curtail

```
sudo add-apt-repository ppa:apandada1/curtail
sudo apt update
sudo apt install curtail
```

I have verified that it can be installed, and it works in KDE Neon 20.04 and also in Xubuntu 20.04 running in my Android phone in Termux (where Flatpak is not available).

Screenshot_20210511_171729
<sup> KDE Neon 20.04 </sup>

Screenshot_2021-05-11-17-12-52-179_com realvnc viewer android
<sup> Ubuntu 20.04 with XFCE in Termux </sup>

The `debian/` directory would make it convenient to quickly build the debian package in Launchpad (also then I won't have to maintain a separate copy). Also, it would make the work easier for a Debian maintainer, in case they want to add it to the Debian repositories. Could you update the Debian changelog when you release a new version?

### CODE REVIEW

**Comment by Huluti** [comment]
@apandada1 I have done a new release and updated the debian changelog. However, I have forgot to update one version string in the release so I've made a patch on flathub: https://github.com/flathub/com.github.huluti.Curtail
Could you do the same on debian ?

**Comment by apandada1** [comment]
@Huluti  Launchpad should build [this](https://github.com/Huluti/Curtail/commit/77750096308b6dc9462ba72e6975ae1d7dced811) commit instead of [this](https://github.com/Huluti/Curtail/commit/ba09dc65238b81f96849d003790c5e89fd5b4774) commit, right? That can be easily done.

Also, I did not update Spanish and Portuguese translations (my username was mentioned in https://github.com/Huluti/Curtail/releases/tag/1.2.0). It must have been a typo.

**Comment by Huluti** [comment]
Exactly for two points.

**Comment by apandada1** [comment]
I have updated the PPA package with the commit containing the new version string
.

**Comment by Huluti** [comment]
Thank you! I think that I'll make a new 1.2.1 release very soon to fix this issue and include a new fix also for #54.

**Comment by apandada1** [comment]
@Huluti  I saw that the latest version requires oxipng. I am not sure how to get that in Ubuntu (it does not seem to be in the repositories), so it may take some time before the new version is released in the PPA.

**Comment by Huluti** [comment]
Yes and a new dep has been added also for SVG support (Scour). Take as many time as you want don't worry :)

**Comment by Huluti** [comment]
@apandada1 There are some errors. I deleted the release and will do a new one in next few days.

**Pull request merged**
