### PR TITLE
Added option to progressive encode jpegs

### PR DESCRIPTION
**Pull request by trst**
Added a toggle to the preferences to enable progressive encoding (i.e. image initially renders the complete image at lower detail and detail is added as the image fully loads, in contrast to the image loading bits from the top to the bottom at full quality). 

Required a few tiny interface changes:

- Adding the 'jpg-progressive' key to gschema
- Adding the interface elements to the preferences.ui
- Adding the logic to check if `jpg-progressive` boolean has been set to
compressor.py
- Adding the logic to add `--all-progressive` flag to jpegoptim in
compressor.py
- Added `jpg-progressive` setting to ui functions in preferences.py

### CODE REVIEW

**Comment by trst** [comment]
Dang, looks like this patch missed the project's name change. What's the best way forward? Rebase on the current master and try pushing the changes again?

**Comment by Huluti** [comment]
Hi! Thank you very much for your PR. I had never really dwelled on this feature but it seems very practical for the web.
Yes I think that you can rebase on master. I'll test it. In any case the code seems very clean to me. Thanks for your time.

**Comment by trst** [comment]
Okay, I've rebased off of upstream. I think this PR should be reviewed pretty carefully now that's all done :sweat_smile:

**Comment by Huluti** [comment]
Ah.. the commit contains all the previous changes. What do you think about forking Curtail and reapply your changes on a new PR? It's maybe the simpler? Thank's in advance and sorry for this inconvenience...

**Comment by Huluti** [comment]
Replaced by #48. Thank's again!

**Pull request closed without merging**
